# Generated by Django 4.2.27 on 2026-01-08 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_profile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-member_since', 'user']},
        ),
    ]
