# Generated by Django 4.2.27 on 2026-01-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_profile_options_profile_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='excerpt',
            field=models.TextField(max_length=120),
        ),
    ]
