# Generated by Django 4.2.27 on 2026-01-13 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_alter_profile_excerpt'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('availability_status', models.IntegerField(choices=[(0, 'Open'), (1, 'Booked')], default=0)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='market.profile')),
            ],
            options={
                'unique_together': {('mentor', 'date', 'start_time', 'end_time')},
            },
        ),
    ]
