# Generated by Django 4.2.27 on 2026-01-21 12:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
