# Generated by Django 4.2.27 on 2026-01-13 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0006_timeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Open'), (1, 'Booked')], default=1)),
                ('visitor_name', models.CharField(max_length=100)),
                ('visitor_email', models.EmailField(max_length=254)),
                ('visitor_phone', models.CharField(max_length=25)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('time_slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='market.timeslot')),
            ],
            options={
                'ordering': ['-booked_at'],
            },
        ),
    ]
