# Generated by Django 4.2.27 on 2026-01-12 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0004_alter_profile_options_profile_updated_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.IntegerField(choices=[(0, 'Open'), (1, 'Booked')], default=0)),
                ('visitor_name', models.CharField(max_length=100)),
                ('visitor_email', models.EmailField(max_length=254)),
                ('visitor_phone', models.CharField(max_length=25)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='market.profile')),
            ],
            options={
                'ordering': ['-date', '-start_time'],
                'unique_together': {('mentor', 'date', 'start_time', 'end_time')},
            },
        ),
    ]
