# Generated by Django 4.2.27 on 2026-01-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.AlterField(
            model_name='booking',
            name='visitor_phone',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
